import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom
from jinja2 import Environment, FileSystemLoader


REPO_JSON_PATH = 'data/repos.json'
TEMPLATE_PATH = 'templates/repo_template.html'
OUTPUT_DIR = 'repositories'
SITEMAP_PATH = 'sitemap.xml'
BASE_URL = 'https://smartlegionlab.ru'


BASE_PAGES = [
    {'loc': f"{BASE_URL}/", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '1.0'},
    {'loc': f"{BASE_URL}/about.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.8'},
    {'loc': f"{BASE_URL}/skills.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.8'},
    {'loc': f"{BASE_URL}/projects.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.9'},
    {'loc': f"{BASE_URL}/research.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.9'},
    {'loc': f"{BASE_URL}/packages.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.8'},
    {'loc': f"{BASE_URL}/articles.html", 'lastmod': '2026-03-06', 'changefreq': 'weekly', 'priority': '0.8'},
]


LANGUAGE_COLORS = {
    'Python': '#3572A5', 'JavaScript': '#f1e05a', 'HTML': '#e34c26',
    'CSS': '#563d7c', 'TypeScript': '#2b7489', 'Shell': '#89e051',
    'Dockerfile': '#384d54', 'Jupyter Notebook': '#DA5B0B',
    'PHP': '#4F5D95', 'Java': '#b07219', 'C++': '#f34b7d',
    'C#': '#178600', 'Ruby': '#701516', 'Go': '#00ADD8', 'Rust': '#dea584'
}


def ensure_dir(directory):
    Path(directory).mkdir(parents=True, exist_ok=True)
    print(f"📁 The directory is ready: {directory}")


def clean_output_directory(directory):
    if os.path.exists(directory):
        shutil.rmtree(directory)
        print(f"🧹 The old directory has been removed: {directory}")
    ensure_dir(directory)


def format_date(date_string):
    if not date_string:
        return ''
    try:
        d = datetime.fromisoformat(date_string.replace('Z', '+00:00'))
        return d.strftime('%b %d, %Y')
    except:
        return date_string[:10]


def format_date_iso(date_string):
    if not date_string:
        return datetime.now().strftime('%Y-%m-%d')
    try:
        d = datetime.fromisoformat(date_string.replace('Z', '+00:00'))
        return d.strftime('%Y-%m-%d')
    except:
        return datetime.now().strftime('%Y-%m-%d')


def generate_repo_pages(repos_data):
    template_dir = os.path.dirname(TEMPLATE_PATH)
    template_file = os.path.basename(TEMPLATE_PATH)
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template(template_file)
    
    generated = []
    
    for repo in repos_data:
        if repo.get('archived'):
            print(f"⏭️  Skipping an archived repo: {repo['name']}")
            continue
        
        size_mb = round(repo.get('size', 0) / 1024, 2)
        license_name = repo.get('license', {}).get('name', '') if repo.get('license') else ''
        
        context = {
            'repo_name': repo['name'],
            'repo_full_name': repo.get('full_name', repo['name']),
            'repo_description': repo.get('description') or 'No description provided.',
            'repo_url': repo['html_url'],
            'language': repo.get('language'),
            'language_color': LANGUAGE_COLORS.get(repo.get('language'), '#8b949e'),
            'stars': repo.get('stargazers_count', 0),
            'forks': repo.get('forks_count', 0),
            'watchers': repo.get('watchers_count', 0),
            'open_issues': repo.get('open_issues_count', 0),
            'created_at': format_date(repo.get('created_at')),
            'updated_at': format_date(repo.get('updated_at')),
            'pushed_at': format_date(repo.get('pushed_at')),
            'size_mb': size_mb,
            'default_branch': repo.get('default_branch', 'main'),
            'license_name': license_name,
            'homepage': repo.get('homepage'),
            'topics': repo.get('topics', []),
            'is_fork': repo.get('fork', False),
            'is_archived': repo.get('archived', False),
            'is_private': repo.get('private', False),
        }
        
        html_content = template.render(**context)
        
        output_path = os.path.join(OUTPUT_DIR, f"{repo['name']}.html")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"✅ Generated by: {output_path}")
        generated.append({
            'loc': f"{BASE_URL}/repositories/{repo['name']}.html",
            'lastmod': format_date_iso(repo.get('pushed_at')),
            'changefreq': 'daily',
            'priority': '0.7'
        })
    
    return generated


def generate_sitemap(repo_urls):
    root = Element('urlset')
    root.set('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9')
    
    for page in BASE_PAGES:
        url_elem = SubElement(root, 'url')
        
        loc = SubElement(url_elem, 'loc')
        loc.text = page['loc']
        
        lastmod = SubElement(url_elem, 'lastmod')
        lastmod.text = page['lastmod']
        
        changefreq = SubElement(url_elem, 'changefreq')
        changefreq.text = page['changefreq']
        
        priority = SubElement(url_elem, 'priority')
        priority.text = page['priority']
    
    print(f"📄 Added base pages: {len(BASE_PAGES)}")
    
    for repo in repo_urls:
        url_elem = SubElement(root, 'url')
        
        loc = SubElement(url_elem, 'loc')
        loc.text = repo['loc']
        
        lastmod = SubElement(url_elem, 'lastmod')
        lastmod.text = repo['lastmod']
        
        changefreq = SubElement(url_elem, 'changefreq')
        changefreq.text = repo['changefreq']
        
        priority = SubElement(url_elem, 'priority')
        priority.text = repo['priority']
    
    print(f"📄 Added repository pages: {len(repo_urls)}")
    
    xml_str = minidom.parseString(tostring(root)).toprettyxml(indent='  ', encoding='utf-8')
    with open(SITEMAP_PATH, 'wb') as f:
        f.write(xml_str)
    
    print(f"✅ Sitemap saved: {SITEMAP_PATH}")
    print(f"   - Total URLs: {len(BASE_PAGES) + len(repo_urls)}")


def main():
    print("🚀 Start generating repository pages...")
    
    if not os.path.exists(REPO_JSON_PATH):
        print(f"❌ File {REPO_JSON_PATH} not found!")
        return
    
    with open(REPO_JSON_PATH, 'r', encoding='utf-8') as f:
        repos_data = json.load(f)
    
    print(f"📦 Loaded {len(repos_data)} repositories from JSON")
    
    clean_output_directory(OUTPUT_DIR)
    
    if not os.path.exists(TEMPLATE_PATH):
        print(f"❌ Template not found: {TEMPLATE_PATH}")
        return
    
    print(f"📄 Template loaded: {TEMPLATE_PATH}")
    
    repo_urls = generate_repo_pages(repos_data)
    print(f"✅ Generated {len(repo_urls)} repository pages")
    
    generate_sitemap(repo_urls)
    
    print("✨ Ready!")


if __name__ == '__main__':
    main()
